import { expect, test } from 'bun:test';
import { overdueStage, reminderWindow, reminderValues, greenSender } from '../supabase/functions/_shared/meta-atrasados-rules';
test('D+1 D+3 D+7 and 10 day boundary', () => { for (const [date,stage] of [['2026-10-07',null],['2026-10-06',1],['2026-10-04',3],['2026-09-30',7],['2026-09-27',7],['2026-09-26',null]] as const) expect(overdueStage(date,'2026-10-07')).toBe(stage); });
test('Sunday blocked and Monday starts at 08 BRT', () => { expect(reminderWindow(new Date('2026-10-11T12:00Z'))).toBe(false); expect(reminderWindow(new Date('2026-10-12T10:59Z'))).toBe(false); expect(reminderWindow(new Date('2026-10-12T11:00Z'))).toBe(true); });
test('client creditor and due date independent for three creditors', () => { for (const [company,label] of [['ume_novo_mundo','NOVO MUNDO'],['mundo_da_moda','UME'],['odres_cred','ODRES CRED']]) expect(reminderValues('Maria',company,'2026-10-06',{'1':'nome','2':'credor','3':'vencimento'},'{{1}} {{2}} {{3}}')).toEqual({'1':'Maria','2':label,'3':'06/10/2026'}); });
test('missing mapping or client blocks values', () => { expect(reminderValues('','odres_cred','2026-10-06',{},'{{1}}')).toBeNull(); expect(reminderValues('Maria','odres_cred','2026-10-06',{'1':'nome'},'{{1}} {{2}}')).toBeNull(); });
test('GREEN confirmed mandatory despite manual release', () => { const inst = {ativo:true,saude_status:'CONNECTED',saude_quality:'GREEN',qualidade_leitura_ok:true,saude_checked_at:new Date().toISOString()}; expect(greenSender(inst)).toBe(true); for(const quality of ['RED','YELLOW','UNKNOWN']) expect(greenSender({...inst,saude_quality:quality,qualidade_liberada_manual:true})).toBe(false); expect(greenSender({...inst,pool_fora_manual:true})).toBe(false); expect(greenSender({...inst,provider:'uazapi'})).toBe(false); });
test('display name and SIP restrictions do not block GREEN messaging', () => {
 const inst={ativo:true,saude_status:'CONNECTED',saude_quality:'GREEN',qualidade_leitura_ok:true,saude_checked_at:new Date().toISOString(),saude_restricoes:{phone_health:{can_send_message:'LIMITED',entities:[{entity_type:'PHONE_NUMBER',can_send_message:'LIMITED',additional_info:['Your display name has not been approved yet.'],errors:[{error_code:138024}]},{entity_type:'APP',can_send_message:'AVAILABLE',errors:[{error_code:138025}]}]},waba_health:{can_send_message:'AVAILABLE'}}};
 expect(greenSender(inst)).toBe(true);
 expect(greenSender({...inst,saude_restricoes:{waba_health:{can_send_message:'BLOCKED'}}})).toBe(false);
 expect(greenSender({...inst,pausa_automatica_motivo:'Meta #131042'})).toBe(false);
});