import { useEffect, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { FunctionsHttpError } from '@supabase/supabase-js';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useCurrentTenantId } from '@/hooks/useTenant';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { TemplateFavoriteSelect } from './TemplateFavoriteSelect';
import { RefreshCw, Save, Pause, Play, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

export function OverdueMetaSettings() {
  const {user}=useAuth(); const tenant=useCurrentTenantId(); const qc=useQueryClient();
  const [selected,setSelected]=useState('novo_lembrete_envio_boleto_variavel'); const [map,setMap]=useState<Record<string,string>>({'1':'nome','2':'credor','3':'vencimento'});
  const [min,setMin]=useState(3); const [max,setMax]=useState(8); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState<any>(null); const [confirm,setConfirm]=useState(false);
  const {data:config}=useQuery({queryKey:['meta-atrasados-config',user?.id,tenant],enabled:!!user,queryFn:async()=>{const {data,error}=await supabase.from('meta_atrasados_config').select('*').eq('owner_id',user?.id||'').eq('tenant_id',tenant).maybeSingle();if(error)throw error;return data;}});
  const {data:templates=[]}=useQuery({queryKey:['meta-atrasados-templates',user?.id,tenant],enabled:!!user,staleTime:300000,queryFn:async()=>{const {data,error}=await supabase.from('meta_templates_mestre').select('nome,idioma,corpo,botoes,cabecalho_tipo').eq('criado_por',user?.id||'').eq('tenant_id',tenant).eq('categoria','UTILITY').order('nome');if(error)throw error;return data||[];}});
  const {data:logs=[]}=useQuery({queryKey:['meta-atrasados-history',config?.id],enabled:!!config?.id,queryFn:async()=>{const {data,error}=await supabase.from('meta_atrasados_envios').select('*').eq('config_id',config?.id||'').order('criado_em',{ascending:false}).limit(50);if(error)throw error;return data||[];}});
  useEffect(()=>{if(config){setSelected(config.template_nome);setMap(config.variaveis_map as Record<string,string>);setMin(config.min_seg);setMax(config.max_seg);}},[config]);
  const template=templates.find(t=>t.nome===selected); const variables=[...new Set(Array.from((template?.corpo||'').matchAll(/\{\{\s*(\w+)\s*\}\}/g),m=>m[1]))];
  const valid=!!template&&variables.every(v=>!!map[v])&&min>=1&&max>min&&max<=60;
  async function save(active:boolean){setBusy(true);try{const {error}=await supabase.rpc('meta_atrasados_salvar',{p_tenant:tenant,p_template:selected,p_idioma:template?.idioma||'pt_BR',p_map:map,p_ativo:active,p_min:min,p_max:max});if(error)throw error;await qc.invalidateQueries({queryKey:['meta-atrasados-config']});toast.success(active?'Lembretes ativados para a próxima rotina diária':'Configuração salva; envios pausados');setConfirm(false);}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar');}finally{setBusy(false);}}
  async function simulate(){setBusy(true);setPreview(null);try{const {data,error}=await supabase.functions.invoke('meta-atrasados',{body:{action:'preview',tenant_id:tenant,template_nome:selected,idioma:template?.idioma||'pt_BR',variaveis_map:map}});if(error){const text=error instanceof FunctionsHttpError?await error.context.text():error.message;let msg=text;try{msg=JSON.parse(text).error||text;}catch{}throw new Error(msg);}if(data?.error)throw new Error(data.error);setPreview(data?.resumos?.[0]);}catch(e){toast.error(e instanceof Error?e.message:'Prévia indisponível');}finally{setBusy(false);}}
  return <section className="space-y-4 border-b pb-6" aria-labelledby="overdue-meta-heading">
    <div className="flex items-center justify-between gap-3 flex-wrap"><h2 id="overdue-meta-heading" className="text-xl font-semibold">Parcelas atrasadas · D+1 / D+3 / D+7</h2><Badge variant={config?.ativo?'default':'secondary'}>{config?.ativo?'ATIVO':'PAUSADO'}</Badge></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Template Utility</Label><TemplateFavoriteSelect tipo="meta" value={selected} onValueChange={v=>{setSelected(v);setPreview(null);setMap({});}} options={templates.map(t=>({value:t.nome,nome:t.nome,idioma:t.idioma,descricao:t.corpo}))}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Intervalo mínimo (s)</Label><Input type="number" min={1} value={min} onChange={e=>{setMin(Number(e.target.value));setPreview(null);}}/></div><div><Label>Intervalo máximo (s)</Label><Input type="number" min={min+1} max={60} value={max} onChange={e=>{setMax(Number(e.target.value));setPreview(null);}}/></div></div></div>
    <div className="grid gap-3 md:grid-cols-3">{variables.map(v=><div key={v}><Label>Variável {'{{'}{v}{'}}'}</Label><Select value={map[v]||''} onValueChange={value=>{setMap(prev=>({...prev,[v]:value}));setPreview(null);}}><SelectTrigger><SelectValue placeholder="Selecionar dado"/></SelectTrigger><SelectContent><SelectItem value="nome">Nome do cliente</SelectItem><SelectItem value="credor">Credor do acordo</SelectItem><SelectItem value="vencimento">Vencimento do boleto</SelectItem></SelectContent></Select></div>)}</div>
    {template&&<div className="border-l-2 border-primary bg-muted/30 p-3 whitespace-pre-wrap text-sm">{template.corpo}</div>}
    <p className="text-sm text-muted-foreground">08:30 BRT · segunda a sábado · até D+10 · somente GREEN · etiqueta do funcionário do acordo</p>
    <div className="flex gap-2 flex-wrap"><Button variant="outline" disabled={busy||!valid} onClick={simulate}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}Conferir destinatários e custo</Button><Button variant="outline" disabled={busy||!valid} onClick={()=>save(false)}><Save className="h-4 w-4"/>Salvar sem ativar</Button>{config?.ativo?<Button variant="secondary" disabled={busy} onClick={()=>save(false)}><Pause className="h-4 w-4"/>Pausar</Button>:<Button disabled title="Aguardando autorização do custo da continuação temporária"><Play className="h-4 w-4"/>Ativação aguardando autorização</Button>}</div>
    {preview&&<div className="space-y-3"><p className="text-sm font-medium">Amostra: {preview.amostra} parcelas · {preview.elegiveis} elegíveis · teto estimado da amostra: {preview.estimativa_brl===null?'Tarifa indisponível':Number(preview.estimativa_brl).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p><p className="text-xs text-muted-foreground">Prévia limitada a {preview.limite_amostra} parcelas; não representa o custo total. Até três mensagens por parcela, cobrança final pela Meta.</p><div className="max-h-80 overflow-auto divide-y">{preview.rows.map((r:any)=><div key={r.pagamento_id} className="py-3 space-y-1"><p className="text-sm font-medium">{r.cliente_nome} · D+{r.etapa} · {r.atendente_nome||'Funcionário indisponível'}</p><p className="text-xs text-muted-foreground">{r.sender?.nome||'Sem instância compatível'} · {r.cliente_telefone||'Sem telefone'}</p><p className="text-sm whitespace-pre-wrap">{r.motivo||r.mensagem}</p></div>)}</div></div>}
    <div className="space-y-2"><div className="flex items-center justify-between"><h3 className="font-medium">Histórico de atrasados</h3><Button size="icon" variant="ghost" aria-label="Atualizar histórico de atrasados" onClick={()=>qc.invalidateQueries({queryKey:['meta-atrasados-history']})}><RefreshCw className="h-4 w-4"/></Button></div>{logs.length===0?<p className="text-sm text-muted-foreground">Nenhum lembrete automático registrado.</p>:<div className="max-h-80 overflow-auto divide-y">{logs.map(l=><div key={l.id} className="py-2"><p className="text-sm">{l.cliente_nome} · D+{l.etapa} · {l.atendente_nome||'—'} <Badge variant={l.status==='aceito'?'secondary':'outline'}>{l.status==='aceito'?'Aceito pela Meta':l.status==='reservado'?'Em processamento / conferir':l.status}</Badge></p><p className="text-xs text-muted-foreground">{new Date(l.atualizado_em).toLocaleString('pt-BR')} · {l.instancia_nome||'Sem remetente'} · {l.motivo||l.wa_message_id}</p></div>)}</div>}</div>
    <Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>Ativar lembretes pagos?</DialogTitle></DialogHeader><p className="text-sm">Até três mensagens por parcela pendente. Os envios começam na próxima rotina diária e param quando a parcela for paga. Sem instância GREEN compatível, o lembrete ficará pendente.</p><p className="text-sm">A estimativa apresentada cobre apenas a amostra. A continuação opera por até três horas e encerra ao concluir. O template mantém o texto “vence em”.</p><DialogFooter><Button variant="outline" onClick={()=>setConfirm(false)}>Cancelar</Button><Button disabled={busy} onClick={()=>save(true)}>Confirmar ativação</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}