INSERT INTO public.meta_template_ideias (nome_sugerido, categoria, idioma, corpo, justificativa, status) VALUES
('lead_boas_vindas_interesse', 'UTILITY', 'pt_BR', 'Olá {{1}}, tudo bem? Vi que você demonstrou interesse em melhorar a presença da sua empresa no Google e no WhatsApp. Posso te explicar em 1 minuto como funciona?', 'Abertura neutra para leads captados no Google Maps. Categoria UTILITY exige contexto de interesse prévio — se a Meta reprovar, suba como MARKETING.', 'rascunho'),
('lead_retorno_contato', 'UTILITY', 'pt_BR', 'Oi {{1}}! Estou retornando ao seu contato sobre atendimento pelo WhatsApp. Você ainda tem interesse em receber mais detalhes?', 'Tom de continuação de conversa, baixo atrito. Se reprovar em UTILITY, subir como MARKETING.', 'rascunho'),
('lead_apresentacao_simples', 'UTILITY', 'pt_BR', 'Olá {{1}}, aqui é da equipe de atendimento. Seu estabelecimento apareceu na nossa pesquisa e gostaríamos de apresentar uma novidade que pode ajudar no seu dia a dia. Posso enviar?', 'Abertura curta pedindo permissão — reduz bloqueio e melhora taxa de resposta. Se reprovar em UTILITY, subir como MARKETING.', 'rascunho'),
('lead_diagnostico_google', 'MARKETING', 'pt_BR', 'Olá {{1}}, notei que sua empresa tem poucas avaliações no Google. Trabalhamos com melhoria de presença digital e posso te mostrar gratuitamente como se destacar. Quer receber?', 'Oferta de diagnóstico gratuito — alto gancho para clínicas e prestadores locais.', 'rascunho'),
('lead_agenda_horarios', 'MARKETING', 'pt_BR', 'Oi {{1}}! Muitas empresas do seu segmento perdem clientes por demora no atendimento. Posso te mostrar como organizar agendamentos automáticos pelo WhatsApp?', 'Dor real de clínicas/estéticas: agendamento. Boa taxa de resposta automática.', 'rascunho'),
('lead_site_institucional', 'MARKETING', 'pt_BR', 'Olá {{1}}, sua empresa tem potencial no Google mas ainda não tem um site próprio. Podemos criar um site profissional em poucos dias. Posso te mandar um exemplo?', 'Leads sem site extraídos do Google Maps respondem bem a oferta de site.', 'rascunho'),
('lead_atendimento_automatico', 'MARKETING', 'pt_BR', 'Oi {{1}}! Você já pensou em atender seus clientes automaticamente no WhatsApp, 24 horas por dia? Posso te mostrar como funciona.', 'Oferta de automação de atendimento — engaja comerciantes e clínicas.', 'rascunho'),
('lead_avaliacoes_reputacao', 'MARKETING', 'pt_BR', 'Olá {{1}}, avaliações positivas no Google aumentam em até 30% os clientes que entram em contato. Posso te enviar dicas gratuitas para melhorar sua reputação?', 'Gancho educativo (dicas grátis) — baixa rejeição, boa resposta.', 'rascunho'),
('lead_certificado_digital', 'MARKETING', 'pt_BR', 'Oi {{1}}! Precisa de certificado digital para sua empresa? Emitimos com agilidade e suporte completo. Posso te passar os valores?', 'Direcionado a contadores e empresas que usam certificado digital.', 'rascunho'),
('lead_parceria_local', 'MARKETING', 'pt_BR', 'Olá {{1}}, estamos buscando parceiros no seu segmento na sua região. Teria interesse em uma conversa rápida sobre uma possível parceria?', 'Abordagem de parceria — tom menos comercial, boa aceitação.', 'rascunho'),
('lead_followup_sem_resposta', 'UTILITY', 'pt_BR', 'Olá {{1}}, só passando para confirmar se você recebeu nossa mensagem anterior. Se não tiver interesse, pode desconsiderar. Obrigado!', 'Follow-up leve após primeiro contato sem resposta. Se reprovar em UTILITY, subir como MARKETING.', 'rascunho'),
('lead_pesquisa_rapida', 'UTILITY', 'pt_BR', 'Oi {{1}}! Estamos fazendo uma pesquisa rápida com empresas do seu segmento. Você pode responder em 10 segundos? 1 - Sim  2 - Não', 'Formato de pesquisa com resposta numérica — maximiza respostas automáticas e manuais.', 'rascunho');